### ISSUE TITLE
how should wet.paths look like?

### ISSUE THREAD

**Issue by danyaljj** [sdadas/commoncrawl-downloader#1]
Thanks for sharing your nice code! 
Could you describe (possibly in your readme) what should the `wet.paths` look like? Any examples/pointers?

**Comment by danyaljj** [comment]
For instance, should it look like this? 
https://github.com/danyaljj/common_crawl_scripts/blob/master/data/cc-index.paths

**Comment by danyaljj** [comment]
I guess not, since I am getting these errors: 
```
java.lang.IllegalArgumentException: Invalid warc format in file cdx-00013.gz
        at pl.sdadas.commoncrawl.process.CCWetReader.call(CCWetReader.java:61)
        at pl.sdadas.commoncrawl.process.CCWorker.call(CCWorker.java:48)
        at pl.sdadas.commoncrawl.process.CCWorker.call(CCWorker.java:16)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
01:39:29.949 [pool-1-thread-4] INFO  p.s.commoncrawl.process.CCWorker - Startring part cc-index/collections/CC-MAIN-2020-10/indexes/cdx-00016.gz
01:39:29.949 [pool-1-thread-4] INFO  p.s.commoncrawl.process.CCDownloader - Downloading https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2020-10/indexes/cdx-00016.gz to /net/nfs2.corp/aristo/danielk/commoncrawl_data/temp/cdx-00016.gz
java.lang.IllegalArgumentException: Invalid warc format in file cdx-00012.gz
        at pl.sdadas.commoncrawl.process.CCWetReader.call(CCWetReader.java:61)
        at pl.sdadas.commoncrawl.process.CCWorker.call(CCWorker.java:48)
        at pl.sdadas.commoncrawl.process.CCWorker.call(CCWorker.java:16)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
01:39:30.465 [pool-1-thread-3] INFO  p.s.commoncrawl.process.CCWorker - Startring part cc-index/collections/CC-MAIN-2020-10/indexes/cdx-00017.gz
01:39:30.465 [pool-1-thread-3] INFO  p.s.commoncrawl.process.CCDownloader - Downloading https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2020-10/indexes/cdx-00017.gz to /net/nfs2.corp/aristo/danielk/commoncrawl_data/temp/cdx-00017.gz
```

**Comment by danyaljj** [comment]
Solved it: I just had to download the latest file from the CC website!

**Comment by danyaljj** [comment]
Thanks for the code again; I have tried multiple codes online, and none really worked. This was pretty convenient!
